apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cryptoapi
  name: cryptoapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cryptoapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cryptoapi
    spec:
      containers:
        - image: amirint/cryptoapi
          name: cryptoapi
          resources: {}
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: config.yml
              subPath: config.yml
              name: config-map
              readOnly: true
      volumes:
        - name: config-map
          configMap:
            name: cryptoapi-config
status: {}
